<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>cfb</AssemblyName>
    <RootNamespace>Cli</RootNamespace>
    <LangVersion>8.0</LangVersion>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- WMI: 把 COM 口映射到 USB VID/PID 以识别烧录器 -->
    <Reference Include="System.Management" />
  </ItemGroup>

</Project>
